import alumni from "./alumni.png"

const RFMWData = [
  {
    requestID: 1,
    requestSenderName: "John Doe",
    requestSenderPhone: "123-456-7890",
    requestSenderEmail: "john.doe@example.com",
    image: alumni,
    AlumniName: "Jane Smith",
    AlumniMail: "jane.smith@example.com",
    AlumniPhone: "987-654-3210",
    message: "Hello, I'd like to connect with you. Hello, I'd like to connect with you. Hello, I'd like to connect with you. Hello, I'd like to connect with you. Hello, I'd like to connect with you. Hello, I'd like to connect with you. Hello, I'd like to connect with you.",
  },
  {
    requestID: 2,
    requestSenderName: "Alice Johnson",
    requestSenderPhone: "555-555-5555",
    requestSenderEmail: "alice.johnson@example.com",
    image: alumni,
    AlumniName: "Bob Williams",
    AlumniMail: "bob.williams@example.com",
    AlumniPhone: "111-222-3333",
    message: "Hi there, I'm interested in your career advice. Hi there, I'm interested in your career advice. Hi there, I'm interested in your career advice. Hi there, I'm interested in your career advice. Hi there, I'm interested in your career advice.",
  },
  {
    requestID: 3,
    requestSenderName: "Eva Davis",
    requestSenderPhone: "777-888-9999",
    requestSenderEmail: "eva.davis@example.com",
    image: alumni,
    AlumniName: "Michael Lee",
    AlumniMail: "michael.lee@example.com",
    AlumniPhone: "444-333-2222",
    message: "Greetings! Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. Let's chat about our industry experiences. ",
  },
  {
    requestID: 4,
    requestSenderName: "Sophia Brown",
    requestSenderPhone: "666-999-8888",
    requestSenderEmail: "sophia.brown@example.com",
    image: alumni,
    AlumniName: "William Hall",
    AlumniMail: "william.hall@example.com",
    AlumniPhone: "123-987-4567",
    message: "Hello, I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities. I'm reaching out to discuss career opportunities.",
  },
  {
    requestID: 5,
    requestSenderName: "Olivia Turner",
    requestSenderPhone: "555-444-3333",
    requestSenderEmail: "olivia.turner@example.com",
    image: alumni,
    AlumniName: "James Wilson",
    AlumniMail: "james.wilson@example.com",
    AlumniPhone: "111-222-3333",
    message: "Hi! Let's connect and share insights. Hi! Let's connect and share insights. Hi! Let's connect and share insights. Hi! Let's connect and share insights. Hi! Let's connect and share insights.",
  },
  {
    requestID: 6,
    requestSenderName: "Lucas Harris",
    requestSenderPhone: "222-333-4444",
    requestSenderEmail: "lucas.harris@example.com",
    image: alumni,
    AlumniName: "Emma Lewis",
    AlumniMail: "emma.lewis@example.com",
    AlumniPhone: "999-888-7777",
    message: "Hello Emma, looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking. looking forward to networking.",
  },
  {
    requestID: 7,
    requestSenderName: "Lily Parker",
    requestSenderPhone: "888-777-6666",
    requestSenderEmail: "lily.parker@example.com",
    image: alumni,
    AlumniName: "Oliver Martin",
    AlumniMail: "oliver.martin@example.com",
    AlumniPhone: "666-555-4444",
    message: "Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends. Hi Oliver, let's discuss industry trends.",
  },
  {
    requestID: 8,
    requestSenderName: "Aiden White",
    requestSenderPhone: "444-555-6666",
    requestSenderEmail: "aiden.white@example.com",
    image: alumni,
    AlumniName: "Mia Robinson",
    AlumniMail: "mia.robinson@example.com",
    AlumniPhone: "777-888-9999",
    message: "Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally. Hello Mia, let's connect professionally.",
  },
  {
    requestID: 9,
    requestSenderName: "Zoe Clark",
    requestSenderPhone: "111-222-3333",
    requestSenderEmail: "zoe.clark@example.com",
    image: alumni,
    AlumniName: "Sophia Turner",
    AlumniMail: "sophia.turner@example.com",
    AlumniPhone: "555-444-3333",
    message: "Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas. Hi Sophia, let's exchange ideas.",
  },
  {
    requestID: 10,
    requestSenderName: "Liam Baker",
    requestSenderPhone: "777-666-5555",
    requestSenderEmail: "liam.baker@example.com",
    image: alumni,
    AlumniName: "Ella Adams",
    AlumniMail: "ella.adams@example.com",
    AlumniPhone: "222-333-4444",
    message: "Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey. Hello Ella, interested in your career journey.",
  },
];

export default RFMWData;
